### PR TITLE
Autoreboot and Quit Confirmation

### PR DESCRIPTION
**Pull request by 2Cubed**
Bot displays custom crash message. Autoreboots after 10 seconds, unless it is killed with Ctrl-C. KeyboardInterrupts now have a quit confirmation.

Hope you like, Para! :)

### CODE REVIEW

**Comment by 2Cubed** [comment]
Just

**Comment by RPiAwesomeness** [comment]
Whoa! Fancy! I like this, definitely merging it in, but could you base it off the 3.3.0 branch instead of master? That's what I'm developing off of right now, and it is what the next full release will be based off of.

**Comment by RPiAwesomeness** [comment]
@2Cubed Done! Here's hoping it works!

**Comment by RPiAwesomeness** [comment]
@2Cubed FYI, if you just hit Enter when asked to confirm if you want to quit, it doesn't actually quit. But if you hit Ctrl-C again later it just quits, no confirmation.

**Pull request merged**
